spring.datasource.url=jdbc:mysql://localhost:3306/micro_yt
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8084/eureka/

# Enable Prometheus Endpoint
management.endpoint.prometheus.enabled=true

# Expose Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Show Health Details
management.endpoint.health.show-details=always

# Optional: Change Actuator Base Path
management.endpoints.web.base-path=/actuator
