spring:
  application:
    name: QUIZ-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/micro_yt
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/

# management:
#   endpoints:
#     web:
#       exposure:
#         include: refresh

dummy:
  data:
    name: Akash not refreshed yet--
